name: unittest run
on: [push]
jobs:
  chack-test-1:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Python3.10
          uses: actions/setup-python@v2
          with:
            python-version: 3.10
        - name: Install dependencies
          run:
            python -m pip install --upgrade pip
            pip install PyYAML
        - name: UnitTest
          run:
            python -m unittest discover tests